// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// On Node.js < 22 (server-side SSR), Supabase realtime-js throws because there is no
// native WebSocket. We pass this stub as the transport to suppress the error at
// createClient() time — REST queries don't open a socket, so the stub is never used.
// In the browser, we use the real WebSocket constructor.
class _SsrWebSocketStub {
  static CONNECTING = 0 as const;
  static OPEN = 1 as const;
  static CLOSING = 2 as const;
  static CLOSED = 3 as const;
  readyState = 3;
  send() {}
  close() {}
  addEventListener() {}
  removeEventListener() {}
  dispatchEvent() { return false; }
}

// Public config — safe to hardcode (anon key is intentionally public)
const SUPABASE_URL_DEFAULT = "https://opryabmiksyvtvqnpvqv.supabase.co";
const SUPABASE_KEY_DEFAULT = "sb_publishable_rlcDB3jUPOvpqGqsrZm9_g_ebN1e2Sx";

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    SUPABASE_URL_DEFAULT;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    SUPABASE_KEY_DEFAULT;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const isServer = typeof window === 'undefined';

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: isServer ? undefined : localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      // Server (Node.js 20): stub suppresses the "no WebSocket" error at init time.
      // REST queries never open a socket so the stub is never actually called.
      // Browser: native WebSocket is passed explicitly to skip the process.versions
      // detection that can misfire when Vite injects a process shim into the bundle.
      transport: isServer ? (_SsrWebSocketStub as unknown as typeof WebSocket) : WebSocket,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

